import { ID_INTERFACE_FIELD } from '../../../shared/enums';

export enum DefaultVisibleFieldsForWorker {
  AMENDMENT = ID_INTERFACE_FIELD.AMENDMENT,
  AMENDMENT_TYPE = ID_INTERFACE_FIELD.AMENDMENT_TYPE,
  QUOTATION = ID_INTERFACE_FIELD.QUOTATION,
  QUOTE_CURRENCY = ID_INTERFACE_FIELD.QUOTE_CURRENCY,
}

export enum DefaultVisibleFieldsForTrader {
  AMENDMENT = ID_INTERFACE_FIELD.AMENDMENT,
  QUOTATION = ID_INTERFACE_FIELD.QUOTATION,
}
