/* eslint-disable */
import { StaticColumnFieldNames } from "./static-column-field-names";

export const STATIC_COLUMN_CAPTION_NAMES: { [key in StaticColumnFieldNames]: string } = {
  [StaticColumnFieldNames.LOT]: 'catalogs.lot',
  [StaticColumnFieldNames.STATUS_NAME]: 'catalogs.applicationStatus',
  [StaticColumnFieldNames.REJECTION_DATE]: 'offer-management.offerDateReject',
  [StaticColumnFieldNames.REJECTION_REASON]: 'offer-management.rejectReason',
  [StaticColumnFieldNames.DIRECTION_NAME]: 'offer-management.offerDirection',
  [StaticColumnFieldNames.DEMOFF_MARKET_TYPES]: 'general.marketType',
  [StaticColumnFieldNames.OFFER_NAME]: 'general.nameProduct',
  [StaticColumnFieldNames.DESCRIPTION]: 'catalogs.shortDesc',
  [StaticColumnFieldNames.GOOD_ANALOG]: 'catalogs.analogs',
  [StaticColumnFieldNames.CREATE_OFFER_DATE]: 'offer-management.offerDate',
  [StaticColumnFieldNames.CONCATED_FIRM_NAME]: 'createOffer.generalInfo.participant',
  [StaticColumnFieldNames.CONTRACT_TYPE]: 'general.contractType',
  [StaticColumnFieldNames.CLIENT]: 'filters.brokerClient',
  [StaticColumnFieldNames.BRANCH]: 'filters.listBranchs',
  [StaticColumnFieldNames.TRADER]: 'offer-management.trader',
  [StaticColumnFieldNames.VOLUME]: 'general.quantity',
  [StaticColumnFieldNames.LOT_SUMMARY_VOLUME]: 'catalogs.totalVolume',
  [StaticColumnFieldNames.UNIT]: 'general.unit',
  [StaticColumnFieldNames.CURRENCY]: 'filters.currency',
  [StaticColumnFieldNames.PRICE]: 'createOffer.good.priceWithoutVAT',
  [StaticColumnFieldNames.VAT_PERCENT]: 'createOffer.total.VAT',
  [StaticColumnFieldNames.AMOUNT_VAT]: 'createOffer.total.amountVAT',
  [StaticColumnFieldNames.LOT_SUMMARY_VAT_AMOUNT]: 'catalogs.totalAmountVAT',
  [StaticColumnFieldNames.TOTAL_AMOUNT]: 'catalogs.costVAT',
  [StaticColumnFieldNames.LOT_SUMMARY_TOTAL_AMOUNT]: 'catalogs.totalCostVAT',
  [StaticColumnFieldNames.SESSION_NUMBER]: 'sessions-schedule.sessionNumber',
  [StaticColumnFieldNames.SESSION_NAME]: 'catalogs.sessionName',
  [StaticColumnFieldNames.SESSION_DATE_AND_TIME]: 'sessions-schedule.DateTimeSession',
  [StaticColumnFieldNames.SESSION_STAGE]: 'sessions-schedule.sessionStage',
  [StaticColumnFieldNames.DELIVERY_CONDITIONS]: 'createOffer.stepName.termsDeliveryTime',
  [StaticColumnFieldNames.DELIVERY_CONDITIONS_PERIOD]: 'createOffer.deliveryTime.deliveryTime',
  [StaticColumnFieldNames.DELIVERY_SCHEDULE]: 'createOffer.paymentDeliveryTerms.deliverySchedule',
  [StaticColumnFieldNames.PAYMENT_CONDITIONS]: 'createOffer.termsPayment.termsPayment',
  [StaticColumnFieldNames.IMPORT_DOMESTIC_DETAILS]: 'offer-management.additionalTermsDomestic',
  [StaticColumnFieldNames.COMMON_DETAILS]: 'createOffer.commonParameters.additionalTerms',
  [StaticColumnFieldNames.EXPORT_DETAILS]: 'offer-management.additionalTermsForeign',
  [StaticColumnFieldNames.ATTACHED_FILES]: 'viewOffer.attachedFiles',
  [StaticColumnFieldNames.PRIVATE_FILES]: 'offer-management.hiddenFiles',
  [StaticColumnFieldNames.PUBLIC_FILES]: 'offer-management.commonFiles',

};
