/* eslint-disable */
export enum STATUS_DOUMENTS {
  DOWNLOAD = 1,
  ERROR,
  IS_BEING_FORMED,
}

export enum SECTIONS_TYPES {
  METALL = 1,
  TIMBER,
  AGRI,
  PROCUREMENT_ICG,
  EXCHANGE_ICG,
  PETROLEUM,
  PERSPECTIVE,
}

export enum REPORT_TYPES {
  TRADING_COURSE_FOR_MIA = 1,
  TRANSACTIONS_FOR_MIA_MTD,
  BIDS_FOR_TRADING_SESSION,
  UNCONSUMED_AMOUNTS,
  TRADING_COURSE_FOR_EAC,
  SUPPLY_CATALOGUE,
  DEMAND_CATALOGUE,
  OFFERS_MANAGEMENT,
}
